name: analytics_engineering_task
version: '1.0.0'
config-version: 2
profile: analytics_engineering_task
model-paths: [models]
seed-paths: [seeds]
test-paths: [tests]
models:
  analytics_engineering_task:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
seeds:
  analytics_engineering_task:
    +quote_columns: false
